
## name: Selene Abyss
## license: MIT
## author: envoidia
## upstream: https://github.com/envoidia/misc-config/blob/main/home/.config/kitty/themes/selene_abyss.conf


background #000000
foreground #ffffff
selection_background #172038
selection_foreground #73bed3
url_color #73bed3
cursor #73bed3
cursor_text_color #172038

# Tabs
active_tab_background #bb94de
active_tab_foreground #402751
inactive_tab_background #73bed3
inactive_tab_foreground #172038

# Windows
active_border_color #bb94de
inactive_border_color #253a5e

# colors 1, 3, 4, 7, 9, 11, 12, 14, 15, 16, and 17 are the same as tokyo night

# normal
color0 #000000
color1 #f7768e
color2 #d9a1d4
color3 #e0af68
color4 #7aa2f7
color5 #a673d3
color6 #73bed3
color7 #a9b1d6

# bright
color8  #253a5e
color9  #ff899d
color10 #e9aee4
color11 #faba4a
color12 #8db0ff
color13 #bb94de
color14 #a4daff
color15 #c0caf5

# extended colors
color16 #ff9e64
color17 #db4b4b
